%%metro title: nf-core/variantprioritization
%%metro logo: nf-core-variantprioritization_logo_dark.png
%%metro file: cna_in | CNA
%%metro file: vcf_in | VCF
%%metro file: report_pcgr | HTML
%%metro line: main | SNV + INDEL | #4CAF50
%%metro line: cna | CNA | #9923A0
%%metro line: reference | Reference | #2196F3

graph LR

    subgraph preprocessing [Pre-processing of vcf files]
        vcf_in[VCF]
        tabix[tabix]
        bcftools_norm[bcftools/norm]
        bcftools_filter[bcftools/filter]

        vcf_in -->|main| tabix
        tabix -->|main| bcftools_norm
        bcftools_norm -->|main| bcftools_filter
    end


    subgraph format_files [Formatting VCF files as pcgr input]
        cna_in[CNA]
        reformat_cna[Reformat CNA]
        reformat_vcf[Reformat VCF]
        intersect[Intersect VCF]
        prepare_pcgr[Prepare VCF]

        reformat_vcf -->|main| intersect
        reformat_vcf -->|main| prepare_pcgr
        intersect -->|main| prepare_pcgr
        cna_in -->|cna| reformat_cna
    end

    subgraph run_pcgr [PCGR]
        get_pcgr[PCGR DB]
        get_vep[VEP Cache]
        pcgr[PCGR]
        report_pcgr[Report]

        get_pcgr -->|reference| pcgr
        get_vep -->|reference| pcgr
        pcgr -->|main,cna| report_pcgr
    end

    %% Inter-section edges
    bcftools_filter -->|main| reformat_vcf
    reformat_cna -->|cna| pcgr
    prepare_pcgr -->|main| pcgr
